services:
  - type: web
    name: case-summarizer
    env: python
    repo: https://github.com/drpsrao3/AI.git
    preBuildCommand: pip install --upgrade pip
    buildCommand: pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu && python -m spacy download en_core_web_sm
    startCommand: bash start.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cs-ai-db
          property: connectionString
      - key: RAZORPAY_KEY_ID
        value: rzp_test_IUOc4j25Yk0fY4
      - key: RAZORPAY_KEY_SECRET
        value: your_newly_generated_key_secret
      - key: RAZORPAY_WEBHOOK_SECRET
        value: webhook_secret_12345
      - key: RAZORPAY_PLAN_ID
        value: plan_QYOJindZWhIN0V
databases:
  - name: cs-ai-db
    databaseName: cs_ai
    user: cs_ai_user